language: ruby

sudo: false
cache: bundler

branches:
  only:
    - master

rvm:
  - 2.5.8
  - 2.6.6
  - 2.7.1
  - jruby

gemfile:
  - gemfiles/Gemfile-rspec-3.7.x
  - gemfiles/Gemfile-rspec-3.8.x
  - gemfiles/Gemfile-rspec-3.9.x
